SET SCHEMA 'asset';
CREATE TABLE IF NOT EXISTS books (
    asset_id SERIAL PRIMARY KEY,
    asset_title VARCHAR(100) NOT NULL,
    symbol VARCHAR(10) NOT NULL,
    category VARCHAR(50) NOT NULL,
    price DECIMAL(15, 2) NOT NULL,
    pricing_source VARCHAR(100),
    currency VARCHAR(10) DEFAULT 'USD',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);